env:
  global:
  - secure: SUgYyq4Z24aCyPsd8PSg1EInLPD0cLMCbEwAlM0mNdpC3MTGuw9zu1NKVEDDLJ/lKgw0C/R4/0oVsV2uuyDINQYZ9toE0noMjnFTszm5JfOr3decfB6GgPkpWwCWPX2eJdVtkdlnPZ0ylFkvGNJtE+lHyBHvS6rQFJFsu26zzGV1LrG6ktmBK2rkfcOLAfhXYdZ2F9jJ3+H/TttHVHVLTV+z57bRa1W4UeAd7hQe25G6L8w0n44fGIldh5gLt799sv1oC0XZ3ToXW7Yblzo8O+i1hiFwif7tXDNuqP1jXETTFxIkXttHxawXg0KE4/3Oc8/JSNeEh6TrQMcg46mYbdNsoZbHD2xLZvlU13/Kyj3UQASYyYOjaHVLlAmQiB2PVmAEo+0x59LmOonNAIi7z3K2uopNc+glPSmFpqTRtcyPlXKfalEdcz2wMByr57XTrJwKdFp2SkydDrF0/d3YeW9GbFISn3cKCgg6usS6gOGF9J9NxfC+xTurb1DuA+Fih5tHHbvwfdMPj7wFIZ/FFIVA6X71n2mv9YwmjXMu00kEc5ZsPNfukfDAyo9XegtbzcGZQTfWZudD/jL8BFawpD9ugTfXiEYpCi/caQn68CJOlALxfUDBKSuHX8PMZJTdhptUYXZtUAqg01z2m26WxqM63nlhstTU2EBbnWUKNfQ=
  - secure: Fal0iAiBfJvuFZRuWjTggB28+UacCZRVpf2uOmMqhdonHitXpOcQd00vNjdvO9jbhTP0q1UnbXJtMVGmAEgeyeydiO1E+CqQHAWC//Q06yzQSBZUneV0kXymomk6efuvRgCWQBY+hq7vu+zukMx1jJ9RsQDNh3fq1ec0TEAm32Dry7Qji5O99SxQzM5wOcXSvcBQfc8j8JhjR/Zuu78gPadwEJ/9/KJ0pmGhBu+etv/LngwfClhoZC9DjZ45M0pF7TFkJrdUWGXbiw4e8cDgUkybe0rIkru4oJNnLMZCgHP/vV/gfYANlz1rEX7xcsR5v5ThJwcIFoqxhjQhe8qULxngVKs9rGiKMEogyyioJZkaTyoq24hFbHiOMIbiOTyT9yjAaBilRkkGA1p927XQ0Z56JwU9aAGq2qHjKxBTJIoi3MjiGsX43UogmPY6P1kYYkbS8/O0cF1pFRyU0RmGPAviwnWVYn6PznnDH8v7CDhWGY1hoKbLwwEyoxk6/zJYEj7Z/GsOaGOiCMNbZA3ybiUUNbBEo5ermwghdCLRAJGFz1mW5hA03Ny+kvdzHPlT+PABX55soHNX2f7iD/6HBxoKkxelbiW3ni+IeyH5McG4pPn78Qhq2shsOENsz7O70KMwmc8dXlWE5DskExET+EzhgjD9qALGBAOQZmrZ0c8=

language: cpp

compiler:
- clang
- gcc

os:
- linux
- osx

branches:
  only:
  - master

before_install:
- echo $TRAVIS_OS_NAME
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install qt5-default qttools5-dev-tools qtmobility-dev qtmultimedia5-dev libqt5svg5-dev; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libfftw3-dev libsndfile1-dev libpulse-dev; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install fftw; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libsndfile; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=/usr/local/opt/qt5/bin:$PATH; fi

script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then qmake dfasma.pro; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then qmake "CONFIG+=fft_fftw3 file_audio_libsndfile" "FILE_AUDIO_LIBDIR=/usr/local/opt/libsndfile" "FFT_LIBDIR=/usr/local/opt/fftw" dfasma.pro; fi
- make
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then macdeployqt dfasma.app -dmg; fi
- ls .

after_success:
    "curl --ftp-create-dirs -T dfasma.dmg -u $FTP_USER:$FTP_PASSWORD ftp://hatchpan.synology.me/home"
