env:
  global:
  - secure: SUgYyq4Z24aCyPsd8PSg1EInLPD0cLMCbEwAlM0mNdpC3MTGuw9zu1NKVEDDLJ/lKgw0C/R4/0oVsV2uuyDINQYZ9toE0noMjnFTszm5JfOr3decfB6GgPkpWwCWPX2eJdVtkdlnPZ0ylFkvGNJtE+lHyBHvS6rQFJFsu26zzGV1LrG6ktmBK2rkfcOLAfhXYdZ2F9jJ3+H/TttHVHVLTV+z57bRa1W4UeAd7hQe25G6L8w0n44fGIldh5gLt799sv1oC0XZ3ToXW7Yblzo8O+i1hiFwif7tXDNuqP1jXETTFxIkXttHxawXg0KE4/3Oc8/JSNeEh6TrQMcg46mYbdNsoZbHD2xLZvlU13/Kyj3UQASYyYOjaHVLlAmQiB2PVmAEo+0x59LmOonNAIi7z3K2uopNc+glPSmFpqTRtcyPlXKfalEdcz2wMByr57XTrJwKdFp2SkydDrF0/d3YeW9GbFISn3cKCgg6usS6gOGF9J9NxfC+xTurb1DuA+Fih5tHHbvwfdMPj7wFIZ/FFIVA6X71n2mv9YwmjXMu00kEc5ZsPNfukfDAyo9XegtbzcGZQTfWZudD/jL8BFawpD9ugTfXiEYpCi/caQn68CJOlALxfUDBKSuHX8PMZJTdhptUYXZtUAqg01z2m26WxqM63nlhstTU2EBbnWUKNfQ=
  - secure: Fal0iAiBfJvuFZRuWjTggB28+UacCZRVpf2uOmMqhdonHitXpOcQd00vNjdvO9jbhTP0q1UnbXJtMVGmAEgeyeydiO1E+CqQHAWC//Q06yzQSBZUneV0kXymomk6efuvRgCWQBY+hq7vu+zukMx1jJ9RsQDNh3fq1ec0TEAm32Dry7Qji5O99SxQzM5wOcXSvcBQfc8j8JhjR/Zuu78gPadwEJ/9/KJ0pmGhBu+etv/LngwfClhoZC9DjZ45M0pF7TFkJrdUWGXbiw4e8cDgUkybe0rIkru4oJNnLMZCgHP/vV/gfYANlz1rEX7xcsR5v5ThJwcIFoqxhjQhe8qULxngVKs9rGiKMEogyyioJZkaTyoq24hFbHiOMIbiOTyT9yjAaBilRkkGA1p927XQ0Z56JwU9aAGq2qHjKxBTJIoi3MjiGsX43UogmPY6P1kYYkbS8/O0cF1pFRyU0RmGPAviwnWVYn6PznnDH8v7CDhWGY1hoKbLwwEyoxk6/zJYEj7Z/GsOaGOiCMNbZA3ybiUUNbBEo5ermwghdCLRAJGFz1mW5hA03Ny+kvdzHPlT+PABX55soHNX2f7iD/6HBxoKkxelbiW3ni+IeyH5McG4pPn78Qhq2shsOENsz7O70KMwmc8dXlWE5DskExET+EzhgjD9qALGBAOQZmrZ0c8=
  - secure: jSA6ObWsXh1+TWrw2PegNhDy7mxE6tL+SdRW/IxvQ9R/GXGkeRK9JM6mENROZsInguSJ7tmM5qj5uYa5PKZg57PzWQEhyZZtWATTnulL4kdE/ah87AaNTpYVXBaEhc37UVqG9OckT2pk0BbpYC0eoA+PhRzNEv8nbESKU/80LJpnnP2XxkbKIy4Q7AIBZllkbcZo4JFZOljiEQF8gWbCJJP4yE0veWPW4A4vuTEgh3zieXQOT6WFx6Zo6XLbuMmv0f3o5QzZIwM/LoXK24bCzi2RkR6u5VoygOEesUu9rk9xAjw7IYSRG8pxi71GaaBbTSmZQ2zQII0ZydN2HtqHQ9UKpwfGirWsLhf+YPkSFb3XFmPMQVHqj50eWQopZdooIbvZ7iQShmc/aeUleoXe0Yk+R4aNjLtQKz7Og/hrchEsjEEdnRw7e6WIgTMaw9XaDHV1hyl8EISYwX5u260w6k8Q9xdVf1h1nDZfnImJrXcQMV7F2akTk4G7vJBN1gJJ5EM2ss585TfyasmhYmXOM95lXseJNYlPmOgD2iIA+HOU+V0gGMMjF24xy7xgjO6tlc2M9DfYdBhM+Vbwz+N8agYMuFCuIoCkJbPEEj2IMsgrCn+Sje+KgpXr3baRWsv4ZGaq8oRU9bdPMD3yA3EWrvSi0DsnrMFIq2/UvjrQxtY=

language: cpp

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

branches:
    only:
        - master

before_install:
    - git fetch --tags
    - git submodule update --init --recursive
    - git describe --tags --always
    - export PROJECTGITVERSION=`git describe --tags --always`
    - echo $PROJECTGITVERSION
    - echo $TRAVIS_OS_NAME
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG

install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install qt5-default qttools5-dev-tools qtmobility-dev qtmultimedia5-dev libqt5svg5-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libfftw3-dev libsndfile1-dev libpulse-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install fftw; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libsndfile; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=/usr/local/opt/qt5/bin:$PATH; fi

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then qmake dfasma.pro; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then qmake "CONFIG+=fft_fftw3 file_audio_libsndfile" "FILE_AUDIO_LIBDIR=/usr/local/opt/libsndfile" "FFT_LIBDIR=/usr/local/opt/fftw" dfasma.pro; fi
    - make
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then macdeployqt dfasma.app -dmg; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mv dfasma.dmg dfasma-$PROJECTGITVERSION.dmg; fi
    - ls .
    #- echo $TRAVIS_TAG

after_success:
    - if [ "$TRAVIS_OS_NAME" = "osx" && "$CC" = "gcc"]; then curl --ftp-create-dirs -T dfasma-$PROJECTGITVERSION.dmg -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_SITE/home/; fi

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LbSkGufUPmCIG9oujJYpySQd4VijFbtR3fP1jH/2DiNMWoZufMUS2wjBLmrfKdxar9eVpbykPFuASw1RhdKsWHKpQuws3qTW12MZcW3XtWVEd3zlA+FCJ4thqZG7G71rJpg5YbeZ1ZdmSJjYd51S9juCpay4chRCTuhwc26fvfW+ZrMEw1+Nky591Sgp4SQpjoXM2itPTyyreVOW6wNeNWZqlcdT38EtU3AMZnXMfuPjojtefNnSKBRgqq4lpuJYyYVvcxqwRXwMQRJ+g3hh8za8jbNuettUFhsXbEupBajtFl9X0aWKBqQgHVRRjHSBvYoWOj7mgmpOIFAczw1UQCklS1Kju/LtBpE/DA0VZmCE0ZNaJ2uvk9t8778nBapUaByTOb3HM4skT0jWcvSV+UFdI2j0TJar21NJOKLDDwT9M86ebgkMipn0YuKCwHaKnKovTT3K3+f+jsmhXbshRA1Kzd1LNiJJQVop/sg7HJTkl+vcBg1ZJ1f/XowZB65R2IauEFZXpk2CFtv7DMZbxOodhioEwAmJgMDX6HYmZ1ng+n/0g55O5B5ODEfUOqRDvenXHfSsr2QZ9q73dXdAVpYRArdrr865/V9k9WyGN/gBIOz3csy9279IiTEPXMCGYdMKGEGMHRQYqDfkDpA2vV9DZtHO8qY9znco/lnGiX0=
  file: dfasma-$PROJECTGITVERSION.dmg
  on:
    repo: gillesdegottex/dfasma
    condition: $TRAVIS_OS_NAME = osx && $CC = gcc
