language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

# whitelist
branches:
  only:
    - master

before_install:
 - echo $TRAVIS_OS_NAME
 # Linux related install
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install qt5-default qttools5-dev-tools qtmobility-dev qtmultimedia5-dev libqt5svg5-dev; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libfftw3-dev libsndfile1-dev libpulse-dev; fi
 # OSX related install
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install fftw; fi
 #- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link --force fftw; fi
# - ls /usr/local/Cellar/fftw/3.3.4
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libsndfile; fi
 #- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link --force libsndfile; fi
# - ls /usr/local/Cellar/libsndfile/1.0.25
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi
 #- ls /usr/local/opt/fftw/*
# - ls /usr/local/opt/qt5
# - ls /usr/local/Cellar/qt5/5.3.2
# - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ls /usr/local/opt/qt5/bin/; fi
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=/usr/local/opt/qt5/bin:$PATH; fi
 #- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link --force qt5; fi

script:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then qmake dfasma.pro; fi
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then qmake "CONFIG+=fft_fftw3 file_audio_libsndfile" "FILE_AUDIO_LIBDIR=/usr/local/opt/libsndfile" "FFT_LIBDIR=/usr/local/opt/fftw" dfasma.pro; fi
 - make
