language: cpp

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

branches:
    only:
        - master

before_install:
    - git submodule update --init --recursive
    - git fetch --tags
    - sleep 1
    - export PROJECTGITVERSION=`git describe --tags --always`
    - echo $PROJECTGITVERSION
    - echo $TRAVIS_OS_NAME
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - export TRAVIS_TAG=`git describe --tags --exact-match HEAD 2>/dev/null`
    - echo $TRAVIS_TAG

install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install qt5-default qttools5-dev-tools qtmobility-dev qtmultimedia5-dev libqt5svg5-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libfftw3-dev libsndfile1-dev libpulse-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install fftw; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libsndfile; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=/usr/local/opt/qt5/bin:$PATH; fi

    # Compile first SDIF itself

script:
    - bash compile_sdif.sh
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then qmake dfasma.pro; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then qmake "CONFIG+=fft_fftw3 file_audio_libsndfile" "FILE_AUDIO_LIBDIR=/usr/local/opt/libsndfile" "FFT_LIBDIR=/usr/local/opt/fftw" dfasma.pro; fi
    - make
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then macdeployqt dfasma.app -dmg; fi
    - sleep 1
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mv dfasma.dmg DFasma-$PROJECTGITVERSION.dmg; fi
    - ls .
    #- echo $TRAVIS_TAG

after_success:
    - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "gcc" ]; then curl --ftp-create-dirs -T DFasma-$PROJECTGITVERSION.dmg -u $FTP_USER:$FTP_PASSWORD ftp://gillesdegottex.eu/; fi

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LbSkGufUPmCIG9oujJYpySQd4VijFbtR3fP1jH/2DiNMWoZufMUS2wjBLmrfKdxar9eVpbykPFuASw1RhdKsWHKpQuws3qTW12MZcW3XtWVEd3zlA+FCJ4thqZG7G71rJpg5YbeZ1ZdmSJjYd51S9juCpay4chRCTuhwc26fvfW+ZrMEw1+Nky591Sgp4SQpjoXM2itPTyyreVOW6wNeNWZqlcdT38EtU3AMZnXMfuPjojtefNnSKBRgqq4lpuJYyYVvcxqwRXwMQRJ+g3hh8za8jbNuettUFhsXbEupBajtFl9X0aWKBqQgHVRRjHSBvYoWOj7mgmpOIFAczw1UQCklS1Kju/LtBpE/DA0VZmCE0ZNaJ2uvk9t8778nBapUaByTOb3HM4skT0jWcvSV+UFdI2j0TJar21NJOKLDDwT9M86ebgkMipn0YuKCwHaKnKovTT3K3+f+jsmhXbshRA1Kzd1LNiJJQVop/sg7HJTkl+vcBg1ZJ1f/XowZB65R2IauEFZXpk2CFtv7DMZbxOodhioEwAmJgMDX6HYmZ1ng+n/0g55O5B5ODEfUOqRDvenXHfSsr2QZ9q73dXdAVpYRArdrr865/V9k9WyGN/gBIOz3csy9279IiTEPXMCGYdMKGEGMHRQYqDfkDpA2vV9DZtHO8qY9znco/lnGiX0=
  file: DFasma-$PROJECTGITVERSION.dmg
  on:
    repo: gillesdegottex/dfasma
    tags: true
    condition: $TRAVIS_OS_NAME = osx && $CC = gcc
