os: Windows Server 2012 R2

platform:
#  - x86
  - x64

configuration:
  - Release

install:
  - set QTDIR=C:\Qt\5.4\msvc2013_64_opengl
  - ps: Get-ChildItem C:\Qt\5.4
  - set PATH=%PATH%;%QTDIR%\bin
  
  - ps: cd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC"
#  - ps: Get-ChildItem .
  - cmd: vcvarsall amd64
  - ps: cd "C:\projects\dfasma"

  - ps: New-Item -ItemType directory -Name lib
  - ps: cd lib
  
  - ps: New-Item -ItemType directory -Name fftw-3.3.4-dll64
  - ps: cd fftw-3.3.4-dll64
#  - echo %CD%
  - appveyor DownloadFile ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4-dll64.zip
  - ps: 7z x fftw-3.3.4-dll64.zip -y
  - ps: lib /machine:x64 /def:libfftw3-3.def
  - ps: Get-ChildItem .
  - ps: cd ..
#  - ps: Get-ChildItem C:\projects\dfasma\lib\fftw-3.3.4-dll32
#  - ps: lib /MACHINE:X86 /def:libfftw3-3.def # Needed only for MSVC (lib is still unrecognized command)

#  - ps: New-Item -ItemType directory -Name libsndfile-1.0.25-w32
#  - ps: cd libsndfile-1.0.25-w32
#  - echo %CD%
# TODO Replace with original
#  - appveyor DownloadFile http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.25-w64-setup.exe
#  - libsndfile-1.0.25-w64-setup.exe /s
#  - ps: Get-ChildItem "C:\Program Files\Mega-Nerd\libsndfile"

  - appveyor DownloadFile http://gillesdegottex.eu/libsndfile-1.0.25-w64.zip
  - ps: 7z x libsndfile-1.0.25-w64.zip -y
#  - ps: lib /MACHINE:X86 /def:libfftw3-3.def # Needed only for MSVC (lib is still unrecognized command)
#  - ps: Get-ChildItem C:\projects\dfasma\lib\libsndfile-1.0.25-w32

# Leave lib folder
  - ps: cd ..
  
# For packaging
# InnoSetup
#     Directly from author (working)
#  - appveyor DownloadFile http://www.jrsoftware.org/download.php/is.exe
#  - is.exe /SP- /VERYSILENT /NORESTART /SUPPRESSMSGBOXES
#     From Choco
  - choco install -y InnoSetup
  - ps: Get-ChildItem "C:\Program Files (x86)\Inno Setup 5"

  - echo %CD%
  
  - git submodule update --init --recursive
#  - ps: cd ..

build_script:
#  - qmake "CONFIG+=fft_fftw3 file_audio_libsndfile" "FILE_AUDIO_LIBDIR=C:\Program Files\Mega-Nerd\libsndfile" "FFT_LIBDIR=C:\projects\dfasma\lib\fftw-3.3.4-dll64" dfasma.pro
  - qmake "CONFIG+=fft_fftw3 file_audio_libsndfile" "FILE_AUDIO_LIBDIR=C:\projects\dfasma\lib\libsndfile-1.0.25-w64" "FFT_LIBDIR=C:\projects\dfasma\lib\fftw-3.3.4-dll64" dfasma.pro
  - set PATH=%PATH%;C:\Qt\Tools\QtCreator\bin
  - C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release
  - ps: Get-ChildItem release
  - ps: '.\distrib\package_appveyor_Win64bit.ps1'
  - ps: Get-ChildItem distrib

artifacts:
  - path: release\dfasma.exe
  - path: distrib\DFasma-*-Win64bit.exe
  
  
